# Generated by Django 4.0.1 on 2022-02-24 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_voie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='voie',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voie',
            name='image',
            field=models.ImageField(upload_to='voies'),
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.site')),
            ],
        ),
        migrations.AddField(
            model_name='voie',
            name='secteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.secteur'),
        ),
        migrations.AddField(
            model_name='voie',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.site'),
        ),
    ]
